### ISSUE TITLE
Add streaming

### ISSUE THREAD

**Issue by johnd0e** [snowby666/poe-api-wrapper#1]
Great work!

And it would be nice to support streaming of Poe responses.

**Comment by Toaster496** [comment]
yess I would like that

**Comment by bleachyin** [comment]
cool! I have a question, shoud i sign up the quora account to get the token? the poe account is not equals quora account right?

**Comment by bleachyin** [comment]
and what's the relationship of quora and poe chatbot?are they the same?

**Comment by snowby666** [comment]
> and what's the relationship of quora and poe chatbot?are they the same?

Poe is a service of quora and it has a backdoor to call its API from quora.

**Comment by snowby666** [comment]
> cool! I have a question, shoud i sign up the quora account to get the token? the poe account is not equals quora account right?

Your poe account is linked to your quora account so basically they re the same.

**Comment by bleachyin** [comment]
but i found when i try to use the poe account to login with quora ,is can't success。maybe their account is not get through each other。and poe chatgpt-4 and claude-100k must with subscribe，how about the quora backdoor?

**Comment by snowby666** [comment]
I meant your poe is linked to quora ofc not vice versa

**Comment by snowby666** [comment]
I've just finished the streaming function, I will add other utilities as well before releasing the new version

**Comment by snowby666** [comment]
I've committed the latest update

**Comment by johnd0e** [comment]
Impressive!

(please unpin closed issues)
