### ISSUE TITLE
API seems down since yesterday

### ISSUE THREAD

**Issue by bluusun** [snowby666/poe-api-wrapper#107]
from poe_api_wrapper import PoeApi

bot = "a2"
message = "What is reverse engineering?"

  File "/opt/homebrew/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 718, in send_message
    raise ValueError(
ValueError: Bot a2 not found. Make sure the bot exists before creating new chat.

**Comment by snowby666** [comment]
theres quick fix for that, u may update the lib to v1.3.7:
```ShellSession
pip install -U poe-api-wrapper
```

**Comment by bluusun** [comment]
Hehe - That was too easy! Thank you so much!
