### ISSUE TITLE
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

### ISSUE THREAD

**Issue by palislau** [snowby666/poe-api-wrapper#114]
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

when can this problem be solved?
啥时候能修好呀大佬

**Comment by PMajesty** [comment]
Use the quora key instead, it works for some reason

**Comment by Evertt** [comment]
Where do I find the quora key? I just knew to get my key from the cookie called `p-b`.

**Comment by PMajesty** [comment]
> Where do I find the quora key? I just knew to get my key from the cookie called `p-b`.
> 
> ### Edit
> can I then somehow use this as an HTTP endpoint without needing to code anything in Python?
> 
> ### Edit 2
> I found some quora related values in my localStorage, but I couldn't get anything to work.
> 
> Is it possible that in my case it won't work, because I created my account on an Apple device via Apple?

What I've done is went on quora, logged it, took the m-b cookie and used THAT instead of my poe key. It worked for me. There's a mini guide in the README

**Comment by Evertt** [comment]
Thank you, that indeed worked.

**Comment by palislau** [comment]
but neither quora key nor poe key works for me, anyone have the same issue?

**Comment by PMajesty** [comment]
Yeah it doesn't work for me anymore. Can't find the solution

**Comment by PMajesty** [comment]
Oh, the dev released a fix. Update the package and read the new readme. It works now 🤦 can't believe I didn't check the releases
