### ISSUE TITLE
zsh: no matches found: poe-api-wrapper[proxy]

### ISSUE THREAD

**Issue by chaovinci** [snowby666/poe-api-wrapper#118]
macbook m3 
pip install -U poe-api-wrapper[proxy]
>> zsh: no matches found: poe-api-wrapper[proxy]

**Comment by Luo-hongyi** [comment]
`pip install -U 'poe-api-wrapper[proxy]'`

note: `[]` have special meaning in zsh

**Comment by snowby666** [comment]
closing since the docs updated
