### ISSUE TITLE
human message id did not found (KeyError)

### ISSUE THREAD

**Issue by skypentum** [snowby666/poe-api-wrapper#120]
When PoeAPI connect using the token, and call function send_message, it responsed key error. 
It was caused to find self.active_messages variable in the recv_post_thread function which didn't define human_message_id key in the api.py file (line 846).

![error](https://github.com/snowby666/poe-api-wrapper/assets/11987376/1be6425b-e060-4124-9a03-e35e6c49ef0f)

**Comment by snowby666** [comment]
human_message_id is no longer used in v1.5.6
