### ISSUE TITLE
Take a look at the code, it stopped working and the basic example of your code no longer works

### ISSUE THREAD

**Issue by noseon** [snowby666/poe-api-wrapper#128]
Take a look at the code, it stopped working and the basic example of your code no longer works

**Comment by snowby666** [comment]
Can you try updating the lib to the 1.4.1 version to check if it works now?

**Comment by noseon** [comment]
After the update it shows this error --> 2024-03-22 18:33:17.473 | DEBUG    | poe_api_wrapper.api:connect_ws:164 - An unknown error occurred. Raw response data: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .big-button,body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .big-button,body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.big-button{border:.063rem solid #0051c3;border-radius:.313rem;font-size:.875rem;line-height:1.313rem;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.big-button:hover{cursor:pointer}.captcha-prompt:not(.hidden){display:flex}@media (width <= 720px){.captcha-prompt:not(.hidden){flex-wrap:wrap;justify-content:center}}.pow-button{background-color:#0051c3;color:#fff;margin:2rem 0}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "www.quora.com",cType: 'managed',cNounce: '97788',cRay: '868844ec292931f7',cHash: '53717943f6dffee',cUPMDTk: "\/poe_api\/gql_POST?__cf_chl_tk=ClBT8lRF3ozM8yw0DlGU609WQbhmEGn2EH76fZ4Ouko-1711132397-0.0.1.1-1599",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/poe_api\/gql_POST?__cf_chl_f_tk=ClBT8lRF3ozM8yw0DlGU609WQbhmEGn2EH76fZ4Ouko-1711132397-0.0.1.1-1599",md: "wv1hgd7O7BFjX3UMPJtH.Qk1LrUh82TieXFRnLTDCX4-1711132397-1.1.1.1-EimR_BS4rjAHY41ze15XeXJwvHlC8Bx7H4VswwkgVCOUPEgh9_.C4PcpgyMz7UoSHZhXb10uiCqpMJVfUIS86_GpyPO0TIk5HJrp3xwyE7uPrUlr9ftBtA1pnGUp21pBHSKd26dtLl4rc8Fd_sY01zI9VOHYp5RgS5Uz8aubXCTU2G.DAbOZPudtsIpgTnGHboYDwU9MajZG5M6gXid8Uq6i2JkOxe3g.SNeDN4WAVhMIFl_IZ8hn6tiqk1dyN6Cxldj4RnbrSfgcCaNAe.EynnzEHLDULUM3FK84A0xHUQ4LtWZianQj_3yawybySDOb3eojmN7PYsw1JeXlaKPgqJhTXNOCQFpMKlGBlSQT7KesVJuZXG2OJtO21hTqjFJ9fteA06dQxThihxxjW_Wd7te5LP3oGgP9V4XooMJTuSkGo5X.jjdKt_SkpXNIaFdtdxdc7zLMpaKoklJutugRDacjKzfu5ErEQO5gjrSZdb4DG9wviL6vZKOsVIeQUMJlBHmS4X_XZEig3KvV_EKeR3ccp_mg_cW_Mbq7zaS6.ukfIhbocOam_h08e0nYoHiyCCS2Q4W8XY58fLFgNkxu37AHu83sVxBt1BsdCMK2XUiZRAWdPAKamVGKLmXjup11.yCbVjoWy9GhSWC4v7LkJ56aPbjHer3dsuqEBmtHk_wjfg_dczNDJ1jO0ue56Fp3hrvJCge8CtrIRkRRYAws_55Te0t.4tiJ7qQA8b95SFXJP1..Gyp06wNTMWJkOkV3KjprOzJQjYBUk.eyrjtheKfDbKlLq3y4X1cmSQ0m_aV0rtI1vZwMZG8inP0s4JS_fNzpd1r1s.h5GGK5xm7uiw6XqvlLaobK851EYJe3H6cJTuDTQ_r8jLprV47CIgXCxW28H2Ha4AY3SUFzqARSkopvXTZT9UuTWbJv0me3qYaIvAeVVJrbTyTFZ2DfIz9wnVJJRyd_iqCpJ.FbCiagFHArGAEViiDAk2X7KX9IgbB1oJ0fvm0ZwSagUCxWR0XeLc84IYQgGcWv9sTL_PeVcOkGDTE46qFV49gHyuoTkyC7GJ97bRj3N1rAf8oYtpyOeM7DSScly79.lqdbYmtyH3A4uSUru8EKYe_scIWAGGs4VOv9EnFKmGkT81ZLXYD.Blg4_AegsgyF26CSIZlxIkeEmfULi4xMCYDZ0ZkVknrB4xr9IRAkPmH3SYCxztomsSPNjrvv.YbxAsD3IaXOENc4Ckdrxi48zXE0O14wfhffHck0eeRmVr.aTVLNvVzpFo2NaRNtQ5tdXEiIa7obVwL3fkYNUOTy36.J71zIsUAai5DsKYCFxi4GL6SsuaES6h9JpljMVPlQ4ko7fUdhs3cfqbtUGr08fmOHWYEFCJF2FC.5JCnCyvdU2WRtaqWLwdDsbbgKAOBljaWgqZGNW4bN1TiFelMplBeIzTqCW_zEMpR502vbzMBEXt_0FPliVzM4d8dxDBYPdbWNEIf3ir3Js5WhRrJ5_dOEwJ7tn7.NOB_PLhOe8PrdotukjW_",mdrd: "O82CCB4C7vaE3HaHFB5pMLrCGbYSXtMS8mQYgoo4x_c-1711132397-1.1.1.1-mp2bLhLso.wGhhcpC3JaiIkGDe5iastyBIlNA17sI9S..3.PWUo1yNuEcnaUojyLe7k_qbn.uEEcm6p82mJdXHvpe6ialtaPq3DkH_X.TgWSpLH1nozfpShIbIifiR4tbXb7ZrKy6vQ2rMeTKzsUzVW.lhSMAlllHdfiCzfXoAiyc8AHprigq7vZz_xutvLcU1PfU5bXHfr0sp9wNSCzYcUl3BM9kjO6MGntZwAE3903A.NAhcuoJtJnb5eLaeSCg4F5tfwsUQTxhDkFc8rlYjRB9GTCrsKn3YoO7_q_FjK7tmeNt.h54LW.JfvLQradLriSvBJP1oe6a8BxfFOZiO_WachxFw2PS3ail_CUo.p8EIO_A4DHtmc1nUfmHSZG6Bs.I50TcRZ.qyJixh_2KwBAYAF.xbCYykSE2okskE27iluQ3CxfLaQN.iR.WnGrKdF8ENpTOsRomldozCWu96BBClhRiWmearUV6rhQ5CVXDsefHfJqbj5JZQFCE8td45_WNM65BehRHJ3oafeaMS7h7hgRB3cEeaeGroRbidvTA9B0BMZIY.hljUbLosiYfsRh.1iv5XbCSvVtfdsxYh1RRUJkkGfl2vKmzaTdIe5uUUEmhBaKHVtxi6VJq4PH0bsqK3pqLFY.yu09IqHOLWDEaDluHjEIR12YR7DgxCgesglQ4q7rKGKInvnl9GDxFa.DPpn8OmVF_oBgSXbQhi1wmSZk3zi1EDWaNwrrabADHnjwTI7elwkPW0DClDZs9ZNmADDmfpfkheXdiGsN5F7Tbew1PreuAyNXFeanqRwYNtEwofThacG9c1uaHqFsqaRCAUkX6jC91WUFoKiWqwetbQe_Caj.DisWdg7but9pp6gsOwKLC0NgvqN96NjnQBZzsykUaySuS2jUnmRpLtQMsXKvaY6Oxus2Oqwd_U0v7ZsHh7I5O7H8smWjloJyjZ201TcbWRxoR05QObItyyKlmnLGWK479h1X10_G54pqp2xL27Tt3tAQMMWgtKKSmkpWhMCNM4snselChP2JaawakEuTq7pK2Bd8NjtbDP5A8jZGszv0nNroFCvIhcegVeRUWUPa3MVNslgDssZ1tdRyfIcw2Md4xJluigYCE5l0OAOW3sPQkYiQkw1tMFAL1FEJMlWF3_X7avcSx3Q.i.b1Jok0Du1F9Bq8GP8vdjQA7EMgVn34B8lEgyN3kBnqQkq7fUVaeM96xKBL43wiFucUy1sCExlMvexhm0faZQOaeGbfT1EOWBWwJ7hPc_ZsKe51wsr52gowjaLmx4.HVtJ.ZUX_bRqp6M2n5.atn1JPsampEDvXq2yXpUELQIu7mzP5eixY7gvHdp3LzhcyubAeGsuSqG_DpL1N_pa0l6rkaJu3XnBeOp2p_OMLiQ5L2EReUh99GhekPaOq9ouBVKIxJGKmkAnvJVjwN5.hofzWmLwb0UOdSfB3tWHlZMOJ5Vc0Ngq5rTNOzYnM7Iyp_QBo.viUMRsSqgCKwxV1tHlK4qugrBqWcaT38dx7JERO7_B5x0a.mlqRmDxVAYx8ROghuO5tcYW2qc_hHz1ETc2f2OC67bkTaoQfc2TD3n0rsLVcnWvo5DTNOqx.MDvAsOvU_4F92WMnKQVWOQvqtybAQZdzcRVthn07nAA_gVtYpzl_g_OFGy427y.S2bxI1DZGJ87xMZqnb1Oo.oVmWZH1IOeiz.yeUhvZcPLNDQ9_tSDnDuzx1huQx3OYIhWszt3O1aBeiFyNrOlqiVFrYTZ6nFWQLL85y1QMPtxxSqLMCM2WcJ8.HnnGtMhbCtq.JOnv9afsygSZAIkPmETOSviP3wghUgS3GAbuasXMba4G3F26aJKmVKyGSua.w79pPGJUsAy4S2E4gHbqvHPS0UB0fLZjivV9xjlw5bx3zbmZORcL8Ca1P3RQxzEemjqWJuuQARWVQ_PWJFYES2M9YL.MNQ.y7Xm0g5ugXtuecAeigsKqeBuPYTJmHdJ2BFXT9WBbxSh3Yizimfbm9ucrMZUR2jrR1zNPYZBF1O8LM.audWJfUeBIK08imdPEZ78_OIhr1d1MlDz6kz8ZE5BgZBkmyZAdjBs4eKeRWu6OIB.1bG0a5JqMtsX1LRhoQzNlkGUFRWHcoJwovDm1qUhr0Dm0tII.tH0ylAkTr8RrHrsJvLAFg6PJhI_2yUOhdjCtPDo3nTK24w8B8CPFs3yMFOA.MYukBPIuBZvaFKcJwQ2HoAQPLewopj8tzadDo6wSAoW67SygUWhXwyVtoCFrMwDcwghY2CEqdzzLDECFr6dkfb9_EcynovbL0mxLHsjEsOUBMWJ8ajdrqVXyIMM_phI.QOh.v7pRHN2fUbrJQjd4jieEsw4W0ygHyA9aw9RiG1e2nYyRhahPEgllFdG7mAUpNIvYz.IQL4wrbK8plwfHr167OAYP01y4rRyRBWX8Cgdfy6PCFagnkPcdSH0pJ256ZJurTkyV363kh3faJ0nUee4.p0efyyvgdJ_828Vok14fmUExq7XoW8odM_gOrMrSGofoNxLzqkzJkfzgJKJec.IVqxcPJzdBt2mlyhseM97rRfNzqb5BrZoR1DfHB4sQDO9fF43mN1nwqc1zXr_VgC3TrTlIgVo4ddwmECK2K9ER79OECPVOjJ.cslxUTikjH8j0AFtkeDm46gJlRJjfcq7UrCYb0qkwIg7HEF7ky2DhQczL6hHzOm_4XNip7OwEHOM0sE9ZQk1OnIHAgNRYjGUhBd.Mvj8qUqzg5b4s8cDh0_qzZJcxUQP1UI6aPPwDB07xVX8S.QYC4NX8xF5b6Y5y_EPf.GdBeGwYzq2kGvV1krLrH3zD.NRodDw6gwduJjGoz3KgCm2imL1CSo8BGTLM2JcvszJAzIMWg4mcIsEolekal69A2eu1fPaWUSQmG3Cq9ij355XvYYhpWbjzIoVI_sWo2bBWLs3O3XxoU_xVDlkZEUG99KbdvPWKbyoMCMu0eNHtL0YjRNPBu9R0_NeG_9UpU_iqFrufExekn0qea0RGUSCRpXkHx07UjXECUbRIad6EN6XWnq5AT96DR7DSYB5D7xCU4AtO3UFYTmAnYNl5CeBiYWDIzLPaDh.mxXzXzrDOjaVTAXt_yIaOHPOJnPSItKSLX9VXEmSyng",cRq: {ru: 'aHR0cHM6Ly93d3cucXVvcmEuY29tL3BvZV9hcGkvZ3FsX1BPU1Q=',ra: 'TW96aWxsYS81LjAgKEFuZHJvaWQgNC40LjI7IE1vYmlsZTsgcnY6NjAuMCkgR2Vja28vNjAuMCBGaXJlZm94LzYwLjA=',rm: 'UE9TVA==',d: 'GiQl8AChIig6uOZFbu2VdfFe0l+Cm3AQ4pFbpuZneEwvYgPCWFpykMYqEjCnq+7drww5+uI/wGq0JpkfUU/KzDK7tndFzLFL4hziTMSj+/JphylGJ3ONt/rSOY1r6zPifKpEjigye6+13Ut9dK+eEsbkf8v7JM14gonOC7+0/JiUG3vLCfiO1E0umIt3TiyxsdwPZDCdREjuJz2fbavxEB3v4gtVT/U7oEaQPJIYtRIvGNr+Fbo6gtqeyjIXmPUFg0Y5DAkUeDbSlsPLhzS9jFZFF+FRV5yyyRx5ERNXZRKoFXRqanmYB5FNOwI9sWXf1GkW8hcFZ3hbhZa5C2A2iwQRRzmOKkDYKHoRf2hQi62gKNMuZ+CWtyCTfoppPqIDxCM0R+Q8C3DI+VlaSqqpczsgf64ZPYHLRfxdpgIAIpGFaDPNGFv2I7Mhr7c3DHNrWy3fpCHDMtBfL71OuxBNQ47GkrPAejOT71tfFWQjCWFVm6RejmN0O+/p8jkR+XsDreg9Rpvn5Of6TcMe2muPYyFUtMzjK2qaZpKMPFL7rzk5XxfhL9HRtOuMVl23JmQ6Yb00aU8GYHXQiPlzzzniNQ==',t: 'MTcxMTEzMjM5Ny40NjMwMDA=',cT: Math.floor(Date.now() / 1000),m: '8bSbIijFsxzv6AF6vnCvf9cx0FBwqcOF5HHS6H6u/GY=',i1: 'lJP6sDIjZVGZ+Oxw1d8Ybg==',i2: 'HoQAb3hHVVrtDaP2hOCwvQ==',zh: 'qHsZ0oLLDtfeDNGl4L0dV6pCxrTPb47J3uDny5mT/Zc=',uh: 'NETlwP6ntQR8P8hecr9NFLvTnx1GuPGb4cW3vPAG5fE=',hh: 'cAvQqIja+zNMJtErMCl74IKlyjpcaIpalTRRo/lDY4Q=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=868844ec292931f7';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/poe_api\/gql_POST?__cf_chl_rt_tk=ClBT8lRF3ozM8yw0DlGU609WQbhmEGn2EH76fZ4Ouko-1711132397-0.0.1.1-1599" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

**Comment by zukixa** [comment]
this is a cloudflare problem, they're blocking your request, not the wrappers' fault

**Comment by noseon** [comment]
> this is a cloudflare problem, they're blocking your request, not the wrappers' fault

Well, I used Google Colab to run the bots, so if the error you mentioned is true, it will be difficult to use now =/ . but a matter of less than 1 week ago it worked fine

**Comment by zukixa** [comment]
poe itself watches this repo closely so things can change dynamically, it happened in the previous iteration and will continue happening

**Comment by noseon** [comment]
the poe could leave it as official. This api using Telegram is very good

**Comment by YRH0** [comment]
regret

**Comment by bluusun** [comment]
Adding Cloudflare protection is quite common - most sites use that to protect from bad bots.
![iDB 2024-03-28 at 20 53 15](https://github.com/snowby666/poe-api-wrapper/assets/65051271/a2c3318b-151b-4efe-ae03-1a262f23af63)

I feel adding these two cookies (only show on poe.com) will work.

This was also an issue here (and they solved it):

https://github.com/xtekky/gpt4free

**Comment by Cisen07** [comment]
It looks like there are no more p_lat items here
![image](https://github.com/snowby666/poe-api-wrapper/assets/37953238/050e3adf-ba0e-490c-8234-25ed07e5a502)

**Comment by phamxtien** [comment]
> It looks like there are no more p_lat items here

Delete all cookie and login again or use Edge instead Chrome

**Comment by snowby666** [comment]
This is fixed in the v1.4.3. Please check documentation for new config.
