### ISSUE TITLE
Possibility to continue existing Thread keeping it's context

### ISSUE THREAD

**Issue by johnd0e** [snowby666/poe-api-wrapper#13]
At the moment when I choose some thread I get this:
```
Your choice: 2
The selected thread is: 2iy84il2rutw694iwv1
Context is now cleared
```

But there is no sense to explicitly continue existing Thread, unless I want to preserve it's context.

**Comment by snowby666** [comment]
sure I will change this in the future

**Comment by snowby666** [comment]
sure I will change this in the future

**Comment by johnd0e** [comment]
Thank you!
