### ISSUE TITLE
Rate limit exceeded for sending requests to poe.com. Please try again later

### ISSUE THREAD

**Issue by AdeliManesh** [snowby666/poe-api-wrapper#130]
Hello
I am getting this exception for all of my poe tokens and also quera tokens
Rate limit exceeded for sending requests to poe.com. Please try again later.

do we have limit on sending messages per IP ?

**Comment by PMajesty** [comment]
I have that problem for a proxy I rented, but there is no problem with my own VPS server for some reason. Very strange

**Comment by PMajesty** [comment]
Just as I left the last message, my access through a VPS also broke down...

**Comment by AdeliManesh** [comment]
Yes, I have the same problem :/

**Comment by bluusun** [comment]
Same here. When I get access I now have the issue that response shows in web interface but API does not receive it. Possibly a timeout issue.

**Comment by FightingFranky** [comment]
Same problem. I have tried both ways in Quora.com and Poe.com, but they didn't work.

**Comment by bluusun** [comment]
> Same problem. I have tried both ways in Quora.com and Poe.com, but they didn't work.

Where did you find the m-lat token on Quora.com? It is not in my list of cookies.

**Comment by FightingFranky** [comment]
> > Same problem. I have tried both ways in Quora.com and Poe.com, but they didn't work.
> 
> Where did you find the m-lat token on Quora.com? It is not in my list of cookies.

You can log in again to refresh the cookies.

**Comment by hategan** [comment]
I am getting the same error using poe cookies. The reply from the server contains the following

` <div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>`

On a newly created quora account, I do not see an `m-lat` cookie.

**Comment by phamxtien** [comment]
> I am getting the same error using poe cookies. The reply from the server contains the following
> 
> ` <div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>`
> 
> On a newly created quora account, I do not see an `m-lat` cookie.

Delete all cookie and login again.

**Comment by snowby666** [comment]
This is fixed in the v1.4.3. Please check documentation for new config.
