### ISSUE TITLE
Bug on the result from poe --b BKEY --lat LATKEY

### ISSUE THREAD

**Issue by i8890321** [snowby666/poe-api-wrapper#135]
I am trying using the poe in the python, using the command poe --b BKEY --lat LATKEY.

then i tried to chat with a public bot called FoodieExpert. Start the conversation by saying "Introduce a restaurant in Singapore with some dishes".

The result looks like the picture, it repeats some lines a lot of time.

<img width="806" alt="Screenshot 2024-04-05 233435" src="https://github.com/snowby666/poe-api-wrapper/assets/60473188/07117ab6-456b-43f7-ac30-fcf751fb0bab">

**Comment by snowby666** [comment]
Hi, thanks for your report.

This is fixed in v1.4.3+
I've reproduced your bug and it works normally now.
