### ISSUE TITLE
it looks like api died. with the basic code below it doesn't work =/

### ISSUE THREAD

**Issue by noseon** [snowby666/poe-api-wrapper#136]
it looks like api died. with the basic code below it doesn't work =/

![Captura de tela 2024-04-06 203146](https://github.com/snowby666/poe-api-wrapper/assets/11984221/7954cefb-e47a-4861-8874-786c17ca463a)

**Comment by noseon** [comment]
from poe_api_wrapper import PoeApi
# Using poe.com tokens
tokens = {
    'b': '*****',
    'lat': '*****'
}

client = PoeApi(cookie=tokens)
bot = "capybara"
message = "What is reverse engineering?"
# Create new chat thread
# Non-streamed example:
for chunk in client.send_message(bot, message):
    pass
print(chunk["text"])

**Comment by phamxtien** [comment]
Try get cookie of quora.com
