### ISSUE TITLE
Daily Limit Reached

### ISSUE THREAD

**Issue by egcash** [snowby666/poe-api-wrapper#140]
The bot is responding with "Daily limit reached for a2_100k."

I'm not sure whether it's a limitation or ..? ,
According to docs, what does "no limit" mean?

**Comment by egcash** [comment]
I'm using quora's cookies btw

**Comment by chinsulee** [comment]
The same problem,how to solve?

**Comment by phamxtien** [comment]
> The bot is responding with "Daily limit reached for a2_100k."
> 
> I'm not sure whether it's a limitation or ..? , According to docs, what does "no limit" mean?

![image](https://github.com/snowby666/poe-api-wrapper/assets/33739597/14a09366-923e-4b3e-91d9-689b07cfe566)

url: https://poe.com/Claude-instant-100k
