### ISSUE TITLE
Error when uploading file with gemini_1_5_pro_1m

### ISSUE THREAD

**Issue by joja16** [snowby666/poe-api-wrapper#147]
I tried uploading the file and using gemini_1_5_pro_1m but both failed.
I always get the error message "Close Error: I/O operation on closed file"
Do you have any way I can perform other functions similar to gemini_1_5_pro_1m?

![image](https://github.com/snowby666/poe-api-wrapper/assets/100010882/91172f69-6457-46b4-8b75-baba38c712a2)

**Comment by sunnysktsang** [comment]
Hello @joja16,

Thank you for reporting this issue with the gemini_1_5_pro_1m model's file handling. I have also encountered this problem and have developed a fix that addresses the "Close Error: I/O operation on closed file" error.

I've submitted a pull request that improves the file handling logic within the generate_file function to ensure that files are managed properly throughout their lifecycle. This fix should resolve the error you are experiencing.

**Pull Request Details:**

- **PR Link**: [Fix file handling in generate_file function](https://github.com/snowby666/poe-api-wrapper/pull/149)
- **Changes Made**: Utilization of context managers for better file management and additional error handling to prevent premature file closure.

I'd appreciate it if the maintainer could review the pull request at their earliest convenience. This change might also benefit others facing similar issues.

For a temporary workaround, you can manually manage the file opening and closing processes in your code, ensuring that file streams are not closed prematurely until all operations are complete. However, the pull request provides a more robust and permanent solution.

Best regards,
Sunny
