### ISSUE TITLE
16 message/day limit for Poe tokens ?

### ISSUE THREAD

**Issue by AdeliManesh** [snowby666/poe-api-wrapper#150]
Hi, I used to be able to send 100 messages daily with poe tokens, but now this has been limited to 16 messages per day. Is there any solution?

**Comment by AdeliManesh** [comment]
This limit is set from poe.com :/

**Comment by AdeliManesh** [comment]
This limit is set by poe.com :/

**Comment by 7trail** [comment]
If you have multiple emails, you could get multiple sets of cookies and alternate between them programmatically. It shouldn't be against TOS to do that; I looked to make sure before suggesting this, and it seems like it's no more against multiple accounts than it is to use this API (depending on the implementation).
