### ISSUE TITLE
The Server is Down?

### ISSUE THREAD

**Issue by FightingFranky** [snowby666/poe-api-wrapper#161]
RuntimeError: An unknown error occurred. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}

It happened to me quite often these days, does anyone have solutions?

**Comment by 7trail** [comment]
This may be caused by the same API issues as [https://github.com/snowby666/poe-api-wrapper/issues/160](https://github.com/snowby666/poe-api-wrapper/issues/160)

**Comment by FightingFranky** [comment]
> This may be caused by the same API issues as #160

It looks like the Poe official makes a second authentication on acquiring the response...
Anyone who know how to fix this.

**Comment by FightingFranky** [comment]
@snowby666

**Comment by snowby666** [comment]
I've just updated a temp fix. Right now if you are connecting via datacenter or sth similar it will be blocked by cloudflare.

**Comment by FightingFranky** [comment]
> will

You save my ass, thanks

**Comment by FightingFranky** [comment]
> I've just updated a temp fix. Right now if you are connecting via datacenter or sth similar it will be blocked by cloudflare.

You save my ass, thanks

**Comment by SolarDriftCom** [comment]
How do you get the cloud fare cookie tokens? Thanks
