### ISSUE TITLE
RuntimeError: Daily limit reached for gpt4_o.

### ISSUE THREAD

**Issue by KYKKIS2** [snowby666/poe-api-wrapper#166]
![image](https://github.com/snowby666/poe-api-wrapper/assets/44586517/c3d34331-fe39-4911-94af-a291c9d1888e)

As the image states, the gpt4_o model doesn't have a limit, but for some reason after asking it 5 times different stuff it gave me a Daily limit reached for gpt4_o.

Is this normal? Or am i doing something wrong with my code. 

Thanks you.

**Comment by snowby666** [comment]
Poe has a currency system using points (varied by your subscription tier) when sending message.

You can check your remaining points (which refreshed daily) with this:
```py
data = client.get_settings()
print(data)
```

**Comment by Toaster496** [comment]
Is there a way to get around this?

**Comment by snowby666** [comment]
> Is there a way to get around this?

1. Create many accounts (if you have time 🤔) and make a tokens rotator
2. Subscribe to Poe >  1,000,000 compute points per month
