### ISSUE TITLE
bug report: "TypeError: 'coroutine' object is not subscriptable"

### ISSUE THREAD

**Issue by lbqc** [snowby666/poe-api-wrapper#168]
## Bug Report
TypeError: 'coroutine' object is not subscriptable

### Description
When calling `AsyncPoeApi.send_message` methods with a specified `chatId` parameter, an error occurs: 

```
TypeError: 'coroutine' object is not subscriptable
```

The error occurs in the code located at: `envs\poe_wrapper39\lib\site-packages\poe_api_wrapper\async_api.py:494`:
```python
self.current_thread[bot] = await self.get_chat_history(bot=bot)['data'][bot]
```

### Steps to Reproduce
1. Call the `AsyncPoeApi.send_message` method with a specified `chatId` parameter.
2. Call the `AsyncPoeApi.delete_chat` method with a specified `chatId` parameter.

### Resolution
The issue was resolved by modifying the code as follows:

```python
# self.current_thread[bot] = await self.get_chat_history(bot=bot)['data'][bot]
temp = await self.get_chat_history(bot=bot)
self.current_thread[bot] = temp['data'][bot]
```
and
```python
# chatdata = await self.get_chat_history(bot=bot)['data'][bot]
temp = await self.get_chat_history(bot=bot)
chatdata = temp['data'][bot]
```

### Environment
- **Python Version**: 3.9.19
- **pip**: 24.0
- **conda**: 24.5.0
- **Operating System**: windows 11

**Comment by snowby666** [comment]
Thanks for your report. This is resolved.
