### ISSUE TITLE
[Feature]: OpenAI api supports NextChat

### ISSUE THREAD

**Issue by Luo-hongyi** [snowby666/poe-api-wrapper#169]
NextChat use OPTIONS but not POST:

`127.0.0.1:65392 - - [23/Jun/2024:00:30:40] "OPTIONS /v1/chat/completions" 405 31`

**Comment by snowby666** [comment]
I've added this in v1.5.7

**Comment by Luo-hongyi** [comment]
Still doesn't work:

`127.0.0.1:56781 - - [23/Jun/2024:22:49:45] "OPTIONS /v1/chat/completions" 422 82`

**Comment by snowby666** [comment]
can i see your data request:

**Comment by snowby666** [comment]
This is my test:
![image](https://github.com/snowby666/poe-api-wrapper/assets/112873281/60af7dc9-b902-4223-b35c-d5e293e53092)

**Comment by snowby666** [comment]
Your response status is 422 so the request data format may be error:

Example
Correct:
```json
{
	"stream": true,
	"model": "gpt-3.5-turbo",
	"messages": [
                     {"role": "system", "content": "You are a helpful assistant."},
                     {"role": "user", "content": "Who won the world series in 2020?"}
         ]
}
```

Invalid:
```json
{
	"stream": true,
	"model": "gpt-3.5-turbo",
	"messages": [
                     {"role": "system", "content": "You are a helpful assistant."},
                     {"role": "user", "content": "Who won the world series in 2020?"},
         ]
}
```

**Comment by Luo-hongyi** [comment]
CORS error 
```
/#/:1 Access to fetch at 'http://127.0.0.1:8000/v1/chat/completions' from origin 'https://app.nextchat.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by snowby666** [comment]
I've updated new version with cors added

**Comment by Luo-hongyi** [comment]
It works, thank you!

**Comment by Luo-hongyi** [comment]
![image](https://github.com/snowby666/poe-api-wrapper/assets/98020294/f41f37ee-f555-46c1-abab-9e054ff2702d)

Each API call generated a new conversation in Poe. Is there any possibility of improvement?

**Comment by snowby666** [comment]
For now u can do this instead:
![image](https://github.com/snowby666/poe-api-wrapper/assets/112873281/b47ccab5-7d3b-4da7-8b83-aabcc7d217bb)

I'll add custom config in next version
