### ISSUE TITLE
Question : how to connect to POE bot via API to C# CAT tools

### ISSUE THREAD

**Issue by drkhateeb** [snowby666/poe-api-wrapper#171]
How to connect to bots via API to C# desktop applications, I want to use some bots in a translation CAT via a plugin by API
the bots are:
https://poe.com/ArabicTranslatorGPT
https://poe.com/ArabicProofreader
https://poe.com/Harakat
https://poe.com/DetailedAnswersGPT
https://poe.com/TheSynonym
https://poe.com/TheAntonym
-------------
CAT tools repository:
https://github.com/RWS/Sdl-Community
Translation Memory Api

Best Regards

**Comment by 7trail** [comment]
So to my understanding, the primary function of this api is just to wrap the queries in a way that's much easier for the developer to manage. It handles all the web stuff for you.

Correct me if I'm wrong, but you should be able to use this repo as a guide to making your own web requests to POE.
