### ISSUE TITLE
SendMessageMutation request fails starting 2 hours ago

### ISSUE THREAD

**Issue by PMajesty** [snowby666/poe-api-wrapper#179]
```
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\poe_api_wrapper\api.py", line 798, in send_message
    message_data = self.send_request(apiPath, 'SendMessageMutation', variables, file_form)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\poe_api_wrapper\api.py", line 183, in send_request
    raise Exception(
Exception: Sending request SendMessageMutation failed. status_code:200,  Error log: RuntimeError("Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}")
```

IDK what happened, I didn't change anything in my script, but all requests just started failing. Funny thing is - it returns status_code: 200 for some reason...

**Comment by tslearn** [comment]
i have the same bug,  i guess  poe change something in server.

**Comment by veloper** [comment]
Same issue; I'm wondering it's worth popping open chrome dev tools :)

**Comment by veloper** [comment]
![Screen Shot 2024-07-24 at 3 51 06 PM](https://github.com/user-attachments/assets/ce5b379d-f7b7-455e-94ea-fc6d3c23a14c)

Seems like they might have actually lower-cased the first `S` in the path:

```diff
-SendMessageMutation
+sendMessageMutation
```

**Comment by FaTal-error1** [comment]
The problem persists even after changing the "S" in SendMessageMutation to lowercase in the three mentioned files.
`{
    "error": "Error getting response from Poe: Sending request **sendMessageMutation** failed. status_code: 200, Error log: RuntimeError(\"Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}\")"
}
`

**Comment by huiye19** [comment]
How to address this issue?

**Comment by BeetleBobsai79** [comment]
change the hash to
"SendMessageMutation": "b4aff2855bc876361737bcbf5f9310b5da4d3250923894ecb8f339de4c2e3fa3", 

it fixes the problem

**Comment by owlsan49** [comment]
> ![Screen Shot 2024-07-24 at 3 51 06 PM](https://private-user-images.githubusercontent.com/340358/351865228-ce5b379d-f7b7-455e-94ea-fc6d3c23a14c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc0NjEsIm5iZiI6MTcyMTkwNzE2MSwicGF0aCI6Ii8zNDAzNTgvMzUxODY1MjI4LWNlNWIzNzlkLWY3YjctNDU1ZS05NGVhLWZjNmQzYzIzYTE0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMTMyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjI3YzU2MTg5YjlkYjZhMGMzNTE2ZTlhODk2MGIwNjJkYmU3MmFjZjEwYzI4MjdlZmJmNWI3MDcwYjIzZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aWmjc2kSLQ9q6awlFqujA9i5yY-pfmwPINx3uwBmMbU)
> 
> Seems like they might have actually lower-cased the first `S` in the path:
> 
> ```diff
> -SendMessageMutation
> +sendMessageMutation
> ```
> 
> Protocol Inspection:
> 
> ```json
> {
>   "queryName": "sendMessageMutation",
>   "variables": {
>     "chatId": null,
>     "bot": "claude_3_igloo",
>     "query": "hi again",
>     "source": {
>       "sourceType": "chat_input",
>       "chatInputMetadata": {
>         "useVoiceRecord": false
>       }
>     },
>     "clientNonce": "<...>",
>     "sdid": "<...>",
>     "attachments": [],
>     "existingMessageAttachmentsIds": [],
>     "shouldFetchChat": true,
>     "messagePointsDisplayPrice": 200
>   },
>   "extensions": {
>     "hash": "b5694554bb2d91d0226fed35139f1d038fdd0fa30148be02546d0e2afa3e72a4"
>   }
> }
> ```
> 
> with the hash differing from:
> 
> https://github.com/snowby666/poe-api-wrapper/blob/7fef4814d2445aba0a3faf7b9c978735eac36d19/poe_api_wrapper/queries.py#L123
> 
> Confirmed a change worked, making a PR now.
> 
> #180

It doesn't work for me. After doing this fix, I get the same error again.
![image](https://github.com/user-attachments/assets/7acc51b7-c498-4543-8d33-6c4b37fce0a7)

**Comment by PMajesty** [comment]
> > ![Screen Shot 2024-07-24 at 3 51 06 PM](https://private-user-images.githubusercontent.com/340358/351865228-ce5b379d-f7b7-455e-94ea-fc6d3c23a14c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc0NjEsIm5iZiI6MTcyMTkwNzE2MSwicGF0aCI6Ii8zNDAzNTgvMzUxODY1MjI4LWNlNWIzNzlkLWY3YjctNDU1ZS05NGVhLWZjNmQzYzIzYTE0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMTMyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjI3YzU2MTg5YjlkYjZhMGMzNTE2ZTlhODk2MGIwNjJkYmU3MmFjZjEwYzI4MjdlZmJmNWI3MDcwYjIzZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aWmjc2kSLQ9q6awlFqujA9i5yY-pfmwPINx3uwBmMbU)
> > Seems like they might have actually lower-cased the first `S` in the path:
> > ```diff
> > -SendMessageMutation
> > +sendMessageMutation
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Protocol Inspection:
> > ```json
> > {
> >   "queryName": "sendMessageMutation",
> >   "variables": {
> >     "chatId": null,
> >     "bot": "claude_3_igloo",
> >     "query": "hi again",
> >     "source": {
> >       "sourceType": "chat_input",
> >       "chatInputMetadata": {
> >         "useVoiceRecord": false
> >       }
> >     },
> >     "clientNonce": "<...>",
> >     "sdid": "<...>",
> >     "attachments": [],
> >     "existingMessageAttachmentsIds": [],
> >     "shouldFetchChat": true,
> >     "messagePointsDisplayPrice": 200
> >   },
> >   "extensions": {
> >     "hash": "b5694554bb2d91d0226fed35139f1d038fdd0fa30148be02546d0e2afa3e72a4"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with the hash differing from:
> > https://github.com/snowby666/poe-api-wrapper/blob/7fef4814d2445aba0a3faf7b9c978735eac36d19/poe_api_wrapper/queries.py#L123
> > 
> > Confirmed a change worked, making a PR now.
> > #180
> 
> It doesn't work for me. After doing this fix, I get the same error. ![image](https://private-user-images.githubusercontent.com/54353918/352091097-7acc51b7-c498-4543-8d33-6c4b37fce0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjgyMjAsIm5iZiI6MTcyMTkyNzkyMCwicGF0aCI6Ii81NDM1MzkxOC8zNTIwOTEwOTctN2FjYzUxYjctYzQ5OC00NTQzLThkMzMtNmM0YjM3ZmNlMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE3MTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OGU4MTc5NzkzNGJlZmFkZjMwNGQyZTlmOGFmNGQ0MmE2OWM0YWQ3ZWE0YTUwZmY3MjcwNDBmYTcyMzhlM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._yDlp_5FA2_NSurKQWEOjwRsGNq_fSEp7iETsoHqv80)

Try to reinstall the package from the pull request https://github.com/snowby666/poe-api-wrapper/pull/180

**Comment by snowby666** [comment]
This is fixed in the new version. Poe's just changed some of their hashes.
