### ISSUE TITLE
sendMessageMutation request fail

### ISSUE THREAD

**Issue by FaTal-error1** [snowby666/poe-api-wrapper#181]
The problem persists even after changing the "S" in SendMessageMutation to lowercase in the three mentioned files (api.py, async_api.py, queries.py).

{ "error": "Error getting response from Poe: Sending request sendMessageMutation failed. status_code: 200, Error log: RuntimeError(\"Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}\")" }

**Comment by BeetleBobsai79** [comment]
change the hash to
"SendMessageMutation": "b4aff2855bc876361737bcbf5f9310b5da4d3250923894ecb8f339de4c2e3fa3",

in the file queries.py

it fixes the problem

**Comment by snowby666** [comment]
This is fixed from v1.6.1

**Comment by DuyguA** [comment]
Same for me, I use v1.6.2 . I successfully sent messages to GPT4-o, however after 2 hrs started to get this error!
