### ISSUE TITLE
Sending request SendMessageMutation failed.

### ISSUE THREAD

**Issue by litao-kupia** [snowby666/poe-api-wrapper#183]
I get an error 
```
Sending request SendMessageMutation failed. status_code:200,  Error log: RuntimeError("Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}")
```
![screenshot_21](https://github.com/user-attachments/assets/e3beb22d-4b3c-4a2b-8635-b377ebb0706e)

The script has been working till 2 days ago and suddenly stopped working without any change in the code.

Interestingly I can see the Poe app itself shows the interaction with my script and seemingly the script does not wait until the Poe finishes streaming answer.

Below is a relevant snippet.
```python
def query_poe_api(client, message, file_path, chat_code="", bot="gpt4_o"):
    try:
        answer = ""
        for chunk in client.send_message(bot=bot, message=message, file_path=file_path, chatCode=chat_code):
            answer += chunk["response"]
        print(answer)
        return answer
    except Exception as e:
        print(f"Error querying Poe API: {e}")
        return ""
```

**Comment by snowby666** [comment]
Did you update to new version?

**Comment by litao-kupia** [comment]
Do you mean the version of poe-api-wrapper pip lib?
```
pip show poe-api-wrapper
```
I have 1.6.0 that I believe is the latest.
![screenshot_22](https://github.com/user-attachments/assets/2f82ac92-1eaa-45ab-b533-b227937be372)

Please let me know if I am missing anything here.

**Comment by snowby666** [comment]
The latest version is v1.6.2
You might need to upgrade since v1.6.0 is outdated

```py
pip install -U poe-api-wrapper
```

**Comment by litao-kupia** [comment]
Thanks, that resolved the issue. Appreciate the great project and also your help.
