### ISSUE TITLE
Api Wrapper not working

### ISSUE THREAD

**Issue by BeetleBobsai** [snowby666/poe-api-wrapper#186]
Error: Sending request SendMessageMutation failed. status_code:200,  Error log: RuntimeError("Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}")

**Comment by crsec** [comment]
me too

**Comment by LarryUESTC** [comment]
me too

**Comment by huiye19** [comment]
me too

**Comment by BeetleBobsai** [comment]
As a temp fix replace the hash for SendMessageMutation in queries.py from f6c1dfb1b10f314d39c15ab3dcd031b12520725e2171f4f557db6199ca8e35a2 to f5c89844d6cb754038fc6260a37f19c7685390cd3b8e318a7c5627ac5f3b4e7b. I don't know what else is broken.

**Comment by huiye19** [comment]
@BeetleBobsai it works. thx!

> As a temp fix replace the hash for SendMessageMutation in queries.py from f6c1dfb1b10f314d39c15ab3dcd031b12520725e2171f4f557db6199ca8e35a2 to f5c89844d6cb754038fc6260a37f19c7685390cd3b8e318a7c5627ac5f3b4e7b. I don't know what else is broken.

**Comment by snowby666** [comment]
This is fixed in the new version

**Comment by phamxtien** [comment]
Error again :)

**Comment by phamxtien** [comment]
> Error again :(

Fix by https://github.com/snowby666/poe-api-wrapper/issues/189#issuecomment-2334980721
