### ISSUE TITLE
'orjson.JSONDecodeError' when 'response.text' is empty

### ISSUE THREAD

**Issue by jishux2** [snowby666/poe-api-wrapper#195]
I encountered an error while using the `send_request` function in the `poe-api-wrapper`. The error traceback is as follows:

```bash
Traceback (most recent call last):
  File "E:\poe-api-wrapper\poe_api_wrapper\api.py", line 145, in send_request
    json_data = orjson.loads(response.text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
```

I printed the relevant information and found that the `response.text` was successfully obtained in previous attempts until the following situation occurred:

```bash
self.BASE_URL: https://poe.com
payload: {"queryName":"SendMessageMutation","variables":{"chatId":null,"bot":"claude_3_igloo","query":"Your current message context: \nThe most recent message: User: 测试\n\n\n","shouldFetchChat":true,"source":{"sourceType":"chat_input","chatInputMetadata":{"useVoiceRecord":false}},"clientNonce":"GGyzU4KEjT276bzS","sdid":"","attachments":[],"existingMessageAttachmentsIds":[],"messagePointsDisplayPrice":20},"extensions":{"hash":"f5c89844d6cb754038fc6260a37f19c7685390cd3b8e318a7c5627ac5f3b4e7b"}}
headers: {'Content-Type': 'application/json', 'poe-tag-id': '9d5a7276ede12cec3fd7fd386f0fa98e'}
2024-10-06 21:01:19,055 INFO     HTTP Request: POST https://poe.com/api/gql_POST "HTTP/2 200 OK"
response.status_code: 200
response.text:
```

It seems that the `response.text` is empty, which causes `orjson.loads(response.text)` to throw an `orjson.JSONDecodeError`. 

Could you please look into this issue and provide a solution? Thank you!

**Comment by jishux2** [comment]
Update on the issue: I think I've figured out the root cause of the issue. It appears that the `messagePointsDisplayPrice` in the `payload` should correspond to the price of the AI conversation, but it's set to 20 here. It seems the method for obtaining `msgPrice` has changed. I found that by changing all `messagePointsDisplayPrice` values to 380, I can now use Claude 3.5 normally.

**Comment by aforamenta** [comment]
Getting the same error I assume with 
Error: Sending request SendMessageMutation failed. status_code:200,  Error log: JSONDecodeError('Input is a zero-length, empty document: line 1 column 1 (char 0)')

**Comment by aforamenta** [comment]
Seems to happen arbitrarily too. It worked in this run. Ran again, and it broke. When it happens poe.com does not create the thread

**Comment by DuyguA** [comment]
How can one fix the problem?

**Comment by jishux2** [comment]
Previously, if an incorrect price was sent, the API would return a "message_points_display_price_mismatch" message, allowing us to retrieve the correct price information from the response.

However, the current behavior is different. If no price information is provided upfront, the API doesn't respond at all. I've stumbled upon a workaround: by sending a sufficiently large `messagePointsDisplayPrice` value, we can receive a response where we can then extract the correct price information.

**Comment by snowby666** [comment]
This is fixed in the new version

**Comment by jishux2** [comment]
> This is fixed in the new version

And perhaps the BOTS_LIST dictionary needs to be updated to include this entry: `'Claude-3.5-Sonnet': 'claude_3_igloo'`?
