### ISSUE TITLE
Add more models

### ISSUE THREAD

**Issue by doa69** [snowby666/poe-api-wrapper#197]
Like add more models: Llama 3.1 405b and allow to add custom model from poe

**Comment by doa69** [comment]
The base model

**Comment by snowby666** [comment]
I've already specified this in README. You can do this by passing the model name `llama31405bt`. Check models.json file in openai folder. If you need to get a model name then just send a message to the bot on poe.com and use  Dev Tool to check its model name in SendMessageMutation
