### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by doa69** [snowby666/poe-api-wrapper#198]
i installed c++ build tool
Building wheels for collected packages: quickjs
  Building wheel for quickjs (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\quickjs
      copying quickjs\__init__.py -> build\lib.win-amd64-cpython-313\quickjs
      running build_ext
      building '_quickjs' extension
      creating build\temp.win-amd64-cpython-313\Release
      creating build\temp.win-amd64-cpython-313\Release\upstream-quickjs
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCONFIG_VERSION=\"2021-03-27\" -DCONFIG_BIGNUM -IC:\Users\user\AppData\Local\Programs\Python\Python313\include -IC:\Users\user\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcmodule.c /Fobuild\temp.win-amd64-cpython-313\Release\module.obj -Werror=incompatible-pointer-types
      cl : Command line error D8021 : invalid numeric argument '/Werror=incompatible-pointer-types'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2   
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quickjs
  Running setup.py clean for quickjs
Failed to build quickjs
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (quickjs)

**Comment by snowby666** [comment]
Theres no wheel build for python 3.11+
