### ISSUE TITLE
Help, I can't find 'p-lat' in my browser

### ISSUE THREAD

**Issue by juemeishici** [snowby666/poe-api-wrapper#199]
I searched both Google Chrome and Edge Browser, but couldn't find 'p-lat'
![捕获](https://github.com/user-attachments/assets/6a38cede-ebfe-4e21-aad5-225ce512cede)

**Comment by juemeishici** [comment]
chrome：
![捕获1](https://github.com/user-attachments/assets/3c5f76ce-2d8a-4f41-9c5a-4320e8aba85e)

**Comment by snowby666** [comment]
delete your cookies and login again

**Comment by juemeishici** [comment]
> delete your cookies and login again

The problem has been solved according to your method. Thank you very much.
