### ISSUE TITLE
Able to set timeout for waiting response

### ISSUE THREAD

**Issue by ngoduyvu** [snowby666/poe-api-wrapper#20]
When I uploaded a pdf file which has number of page > 50. It took POE AI a while to response but the code return "RuntimeError: Response timed out.". Is it possible if I can set timeout for the function?

![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/bb4d9ed8-e396-4561-93b8-b0024f1853d4)

**Comment by snowby666** [comment]
When I tried to upload a large pdf file (~5mb) to a2, the bot still responds but when it comes to some bots such as Code-Llama, it results in this error "Unable to reach Poe.". Maybe each bot has different capacity to read files.

**Comment by ngoduyvu** [comment]
Oh, I found it as well. Actually, the Web Page keeps sending a POST request to get an answer but since the input file is quite large. The model takes a longer time so the page shows you the message "Unable to reach Poe". If you uploaded the file then wait a bit and keep refreshing the page. You will see the answer.
