### ISSUE TITLE
[Poe] Upload File: Error when try to send a prompt with File upload

### ISSUE THREAD

**Issue by ngoduyvu** [snowby666/poe-api-wrapper#24]
Hi, I think Poe just changed something. Yesterday, I run the the send prompt with file upload and the code run success but now it returns error.

![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/0263e741-c80e-4fa6-b36d-ee59ee327341)

**Comment by snowby666** [comment]
I've just fixed this. I will release the new version soon

**Comment by ngoduyvu** [comment]
Thanks, That is so fast.
