### ISSUE TITLE
delete_chat and purge_conversation can not work

### ISSUE THREAD

**Issue by 4781121** [snowby666/poe-api-wrapper#29]
command: delete_chat(bot, chatId=chat_id)
![QQ截图20230905165143](https://github.com/snowby666/poe-api-wrapper/assets/6317240/741eaa45-fa4a-4606-b01f-1b5952536b5f)

command: purge_conversation(bot, chatId=chat_id)
![QQ截图20230905165316](https://github.com/snowby666/poe-api-wrapper/assets/6317240/637eb619-dff3-4219-aaf4-2020ff80ed36)

how can i fix it? Is it my fault? thank you!

**Comment by snowby666** [comment]
Make sure the bot is a valid bot name and your chatId is int type

**Comment by 4781121** [comment]
thank you!
