### ISSUE TITLE
No response and thread keep increasing.

### ISSUE THREAD

**Issue by zhouhh2017** [snowby666/poe-api-wrapper#31]
Successfully installed poe-api-wrapper-1.2.1 tls-client-0.2.1

Tryed all Send message examples. Thread-99(ws_run_thread)  But nothing feedback.

**Comment by snowby666** [comment]
It will be nice if you can show the error logs

**Comment by zhouhh2017** [comment]
No error occured, just endless loop.

**Comment by zhouhh2017** [comment]
The code:
from poe_api_wrapper import PoeApi
client = PoeApi("06oT..")
bot = "a2"
message = "What is reverse engineering?"
# Non-streamed example:
for chunk in client.send_message(bot, message):
    pass
print(chunk["text"])

**Comment by zhouhh2017** [comment]
I located function #connect_ws
, but it's unclear what caused him to not jump out
def send_message:
...
while self.ws_error:
            sleep(0.01)
print('0')
self.connect_ws()
print('1')

=>
def connect_ws:
print('hello')
  .... all codes in the function
print('bye')


Terminal output:
hello
bye
0
hello
hello
bye
hello
bye

**Comment by snowby666** [comment]
I see. I'll try to resolve this.

**Comment by wacharlin** [comment]
maybe, i  have the same problem.

**Comment by zhouhh2017** [comment]
The update helps.
pip install --upgrade poe-api-wrapper

Successfully uninstalled poe-api-wrapper-1.2.1
Successfully installed poe-api-wrapper-1.2.3

But a New Error occurred:
site-packages\poe_api_wrapper\api.py", line 258, in connect_ws
    raise RuntimeError("Timed out waiting for websocket to connect.")
RuntimeError: Timed out waiting for websocket to connect.

**Comment by wacharlin** [comment]
> The update helps. pip install --upgrade poe-api-wrapper
> 
> Successfully uninstalled poe-api-wrapper-1.2.1 Successfully installed poe-api-wrapper-1.2.3
> 
> But a New Error occurred: site-packages\poe_api_wrapper\api.py", line 258, in connect_ws raise RuntimeError("Timed out waiting for websocket to connect.") RuntimeError: Timed out waiting for websocket to connect.

have you solved? I have the same error as yours.

**Comment by li904775857** [comment]
> 更新有帮助。点子安装 --升级 PoE-API 包装器
> 
> 已成功卸载 poe-api-wrapper-1.2.1 已成功安装 poe-api-wrapper-1.2.3
> 
> 但是发生了一个新错误：站点包\poe_api_wrapper\api.py“，第 258 行，connect_ws引发运行时错误（”等待 websocket 连接超时。运行时错误：等待 websocket 连接超时。

have you solved? I have the same error as yours.

**Comment by phamxtien** [comment]
increase timeout

**Comment by li904775857** [comment]
> increase timeout

我设置的30秒，还是不行，socket，on_error函数返回 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
