### ISSUE TITLE
Ballyregan dependencies

### ISSUE THREAD

**Issue by ImmortalBoi** [snowby666/poe-api-wrapper#39]
Hello, I was wondering if there was a version of this library without Ballyregan, I know it's for proxies but in my case I don't need a proxy and it takes up a massive amount of space without being used. So I was wondering if it was possible to make a version with it removed. Thank you for your time.

**Comment by ImmortalBoi** [comment]
In case anyone else has this niche use case, I forked the repo and removed the proxies.

https://github.com/ImmortalBoi/poe-api-wrapper-proxyless

**Comment by snowby666** [comment]
I've just added this.

**Comment by ImmortalBoi** [comment]
> I've just added this.

Thank you
