### ISSUE TITLE
send_message() return error message

### ISSUE THREAD

**Issue by 4781121** [snowby666/poe-api-wrapper#4]
错误信息:
Fail to get a message. Please try again!
No messages found!

相同代码昨天还没事

**Comment by snowby666** [comment]
some of the old queries are not suitable for the new update so I'm updating the api right now

**Comment by snowby666** [comment]
some of the old queries are not suitable for the new update so I'm updating the api right now

**Comment by 4781121** [comment]
是最新的代码, 我只增加了一个代理设置, 会有如上报错

**Comment by 4781121** [comment]
![image](https://github.com/snowby666/poe-api-wrapper/assets/6317240/cd7557b8-4f94-4439-abf0-ba6578765a9c)
![image](https://github.com/snowby666/poe-api-wrapper/assets/6317240/b078a022-523c-4ad7-9124-682b10a4af98)

只有这点区别

**Comment by snowby666** [comment]
I've just committed the hotfix for recent updates of poe. I will add more features soon

**Comment by snowby666** [comment]
I've just committed the hotfix for recent updates of poe. I will add more features soon.
