### ISSUE TITLE
Using third-party proxy Clash, ballyregan called by PoeApi cannot read proxy information from the system

### ISSUE THREAD

**Issue by srcao-bingo** [snowby666/poe-api-wrapper#41]
When I run the sample code below, I get the following error：

`from poe_api_wrapper import PoeApi

token = "************"

bot = "a2"
message = "What is reverse engineering?"

client = PoeApi(token, proxy=True)

for chunk in client.send_message(bot, message):
  print(chunk["response"], end="", flush=True)`

    client = PoeApi(token, proxy=True)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\poe_api_wrapper\api.py", line 110, in __init__
    proxies = fetch_proxy()
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\poe_api_wrapper\proxies.py", line 19, in fetch_proxy
    proxies = fetcher.get(
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\ballyregan\fetcher.py", line 134, in get
    proxies = self._gather(
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\ballyregan\fetcher.py", line 104, in _gather
    raise NoProxiesFound
ballyregan.core.exceptions.NoProxiesFound: Could not find any proxies

**Comment by caoshuirong** [comment]
I installed poe_api_wrapper[proxy]. My operating system is Win11, and the Python version is 3.9.12

**Comment by snowby666** [comment]
Well there was no proxy at that moment. My unit test still works

**Comment by caoshuirong** [comment]
Did you enable Clash or other proxy software when testing? I keep Clash on when running the sample code.  If I turn off Clash, I can't access Poe.com.

**Comment by caoshuirong** [comment]
![下载_00](https://github.com/snowby666/poe-api-wrapper/assets/60139266/c87cba82-57ce-4a25-a3d5-f259cf6063ee)

**Comment by snowby666** [comment]
i cant help beyond that then since it depends on ballyregan for auto-proxy method. Can you still use the lib with just `client = PoeApi(token)`?

**Comment by caoshuirong** [comment]
I still can't use it. 

   client = PoeApi(token)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\poe_api_wrapper\api.py", line 124, in __init__
    'Quora-Formkey': self.get_formkey,
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\poe_api_wrapper\api.py", line 144, in get_formkey
    response = self.client.get(self.BASE_URL, headers=self.HEADERS, follow_redirects=True)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1041, in get
    return self.request(
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\software\anaconda\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\cao\AppData\Roaming\Python\Python39\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1129)

**Comment by caoshuirong** [comment]
I lowered the version of urllib3 to 1.25.11 and solved the above problem. It shows that the connection is established but another problem occurs. Have you ever encountered this situation?
![2023-09-16_19-27-36](https://github.com/snowby666/poe-api-wrapper/assets/60139266/5ec87505-b11a-4330-a17f-bc4b6d35c25a)

**Comment by wacharlin** [comment]
> I lowered the version of urllib3 to 1.25.11 and solved the above problem. It shows that the connection is established but another problem occurs. Have you ever encountered this situation? ![2023-09-16_19-27-36](https://user-images.githubusercontent.com/60139266/268445444-5ec87505-b11a-4330-a17f-bc4b6d35c25a.jpg)

请问你的问题解决了吗

**Comment by caoshuirong** [comment]
> > I lowered the version of urllib3 to 1.25.11 and solved the above problem. It shows that the connection is established but another problem occurs. Have you ever encountered this situation? ![2023-09-16_19-27-36](https://user-images.githubusercontent.com/60139266/268445444-5ec87505-b11a-4330-a17f-bc4b6d35c25a.jpg)
> 
> 请问你的问题解决了吗

今天重新装了一遍，还是同样的问题，换换别的库吧，别在一棵树上吊死。
![image](https://github.com/snowby666/poe-api-wrapper/assets/60139266/6bf70025-429c-419a-8e82-81eef12145ed)

**Comment by Hecbi** [comment]
他的默认代理检测器找不到clash代理，需要修改他的代码，分为两部分：
1. http代理
2. websocket代理

1. 修改api.py的`__init__` 如下：
```python
def __init__(self, cookie: str, proxy: bool=False):
        self.cookie = cookie
        self.formkey = None
        if proxy == True and PROXY == True:
            # proxies = fetch_proxy()
            # for p in range(len(proxies)):
            try:
                self.proxy = {
                    "http://": "socks5://127.0.0.1:7890",
                    "https://": "socks5://127.0.0.1:7890",
                }
                self.client = Client(headers=self.HEADERS, timeout=180, proxies=self.proxy)
                # logger.info(f"Connection established with {proxies[p]}")
                logger.info("代理连接成功")
                # break
            except:
                # logger.info(f"Connection failed with {proxies[p]}. Trying {p+1}/{len(proxies)} ...")
                logger.error("代理错误")
                sleep(1)
        else:
            self.proxy = None
            self.client = Client(headers=self.HEADERS, timeout=180)
        self.client.cookies.update({'m-b': self.cookie})
        
        self.get_channel_settings()
        
        logger.info("Connection established with poe.com")
        
        self.ws_connecting = False
        self.ws_connected = False
        self.ws_error = False
        self.active_messages = {}
        self.message_queues = {}
        self.current_thread = {}
        self.retry_attempts = 3
        self.message_generating = True
        self.ws_refresh = 3
        self.groups = {}
        
        self.connect_ws()
```

2. 修改api.py的`ws_run_thread`函数如下：
```python
    def ws_run_thread(self):
        if not self.ws.sock:
            kwargs = {"sslopt": {"cert_reqs": ssl.CERT_NONE}, "http_proxy_host":"127.0.0.1", "http_proxy_port": 10808, "proxy_type": "socks5"}
            self.ws.run_forever(**kwargs)
```

这个方法对我好用

**Comment by caoshuirong** [comment]
@Hecbi 首先非常感谢你的分享，我今晚尝试后也能正确识别代理，不过仍存在下面这个问题
![image](https://github.com/snowby666/poe-api-wrapper/assets/60139266/128926f0-9f9b-4e10-85bf-527a4c0aea75)
我分别使用了quora.com 和 poe.com 最新的 token ，也更新了 poe-api-wrapper ，我不太清楚是什么原因导致该问题。如果你曾遇到过相似的问题，方便分享一下你是如何解决的吗？

**Comment by srcao-bingo** [comment]
> @Hecbi 首先非常感谢您的分享，我今晚尝试后也能正确识别代理，不过仍存在下面这个问题 ![image](https://private-user-images.githubusercontent.com/60139266/302113740-128926f0-9f9b-4e10-85bf-527a4c0aea75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDY0NDUsIm5iZiI6MTcwNzE0NjE0NSwicGF0aCI6Ii82MDEzOTI2Ni8zMDIxMTM3NDAtMTI4OTI2ZjAtOWY5Yi00ZTEwLTg1YmYtNTI3YTRjMGFlYTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE1MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMmIwMDg3OTExMDIzZmI5OWY0MWM4ZjI5YWZlNmVjNjVkNzhiODlkMjNmYzk4Y2YyMTZhZTMzMzgyMmQ2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D0DVQmVAcokw_7RxQwCt__9BJZU7CfG7HZnFo3-cdkM) 我分别使用了quora.com 和 poe.com 最新的 token ，也更新了 poe-api-wrapper ，我不太清楚是什么原因导致该问题。如果您曾遇到过相似的问题，方便分享一下您是如何解决的吗？

找到原因了，def ws_run_thread(self) 中的 "http_proxy_port"这个端口号需要修改成自己的端口。
终于可以愉快的玩耍了，再次感谢！

**Comment by mhqsll** [comment]
@srcao-bingo 修改init代码中的 self.client = Client(headers=self.HEADERS, timeout=180, proxies=self.proxy)，Client是从哪里创建的

**Comment by qiuzhen8484** [comment]
> 他的默认代理检测器找不到clash代理，需要修改他的代码，分为两部分：
> 
> 1. http代理：修改api.py的`__init__` 如下：
> 
> ```python
> def __init__(self, cookie: str, proxy: bool=False):
>         self.cookie = cookie
>         self.formkey = None
>         if proxy == True and PROXY == True:
>             # proxies = fetch_proxy()
>             # for p in range(len(proxies)):
>             try:
>                 self.proxy = {
>                     "http://": "socks5://127.0.0.1:7890",
>                     "https://": "socks5://127.0.0.1:7890",
>                 }
>                 self.client = Client(headers=self.HEADERS, timeout=180, proxies=self.proxy)
>                 # logger.info(f"Connection established with {proxies[p]}")
>                 logger.info("代理连接成功")
>                 # break
>             except:
>                 # logger.info(f"Connection failed with {proxies[p]}. Trying {p+1}/{len(proxies)} ...")
>                 logger.error("代理错误")
>                 sleep(1)
>         else:
>             self.proxy = None
>             self.client = Client(headers=self.HEADERS, timeout=180)
>         self.client.cookies.update({'m-b': self.cookie})
>         
>         self.get_channel_settings()
>         
>         logger.info("Connection established with poe.com")
>         
>         self.ws_connecting = False
>         self.ws_connected = False
>         self.ws_error = False
>         self.active_messages = {}
>         self.message_queues = {}
>         self.current_thread = {}
>         self.retry_attempts = 3
>         self.message_generating = True
>         self.ws_refresh = 3
>         self.groups = {}
>         
>         self.connect_ws()
> ```
> 
> 2. websocket代理：修改api.py的`ws_run_thread`函数如下：
> 
> ```python
>     def ws_run_thread(self):
>         if not self.ws.sock:
>             kwargs = {"sslopt": {"cert_reqs": ssl.CERT_NONE}, "http_proxy_host":"127.0.0.1", "http_proxy_port": 10808, "proxy_type": "socks5"}
>             self.ws.run_forever(**kwargs)
> ```
> 
> 这个方法对我好用

请问我使用了这个代码还是连接不上代理应该怎么解决呢？

**Comment by qiuzhen8484** [comment]
> http_proxy_port

请问你现在还能正常使用吗？

**Comment by qiuzhen8484** [comment]
> > 他的默认代理检测器找不到clash代理，需要修改他的代码，分为两部分：
> > 
> > 1. http代理：修改api.py的`__init__` 如下：
> > 
> > ```python
> > def __init__(self, cookie: str, proxy: bool=False):
> >         self.cookie = cookie
> >         self.formkey = None
> >         if proxy == True and PROXY == True:
> >             # proxies = fetch_proxy()
> >             # for p in range(len(proxies)):
> >             try:
> >                 self.proxy = {
> >                     "http://": "socks5://127.0.0.1:7890",
> >                     "https://": "socks5://127.0.0.1:7890",
> >                 }
> >                 self.client = Client(headers=self.HEADERS, timeout=180, proxies=self.proxy)
> >                 # logger.info(f"Connection established with {proxies[p]}")
> >                 logger.info("代理连接成功")
> >                 # break
> >             except:
> >                 # logger.info(f"Connection failed with {proxies[p]}. Trying {p+1}/{len(proxies)} ...")
> >                 logger.error("代理错误")
> >                 sleep(1)
> >         else:
> >             self.proxy = None
> >             self.client = Client(headers=self.HEADERS, timeout=180)
> >         self.client.cookies.update({'m-b': self.cookie})
> >         
> >         self.get_channel_settings()
> >         
> >         logger.info("Connection established with poe.com")
> >         
> >         self.ws_connecting = False
> >         self.ws_connected = False
> >         self.ws_error = False
> >         self.active_messages = {}
> >         self.message_queues = {}
> >         self.current_thread = {}
> >         self.retry_attempts = 3
> >         self.message_generating = True
> >         self.ws_refresh = 3
> >         self.groups = {}
> >         
> >         self.connect_ws()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. websocket代理：修改api.py的`ws_run_thread`函数如下：
> > 
> > ```python
> >     def ws_run_thread(self):
> >         if not self.ws.sock:
> >             kwargs = {"sslopt": {"cert_reqs": ssl.CERT_NONE}, "http_proxy_host":"127.0.0.1", "http_proxy_port": 10808, "proxy_type": "socks5"}
> >             self.ws.run_forever(**kwargs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个方法对我好用
> 
> 请问我使用了这个代码把socket5（直接连不上代理）改为http后，连接上代理了但还是在response_json = self.client.get(f'{self.BASE_URL}/poe_api/settings', headers=self.HEADERS, timeout=30).json() 这一句出现错误EOF occurred in violation of protocol (_ssl.c:1129) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129) 安装的是poe-api-wrapper[proxy]
> 
> ![image](https://private-user-images.githubusercontent.com/35674925/328376327-3a2552f8-f420-47e8-96ac-ffe1d04bbd05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIyNzMsIm5iZiI6MTcxNTE2MTk3MywicGF0aCI6Ii8zNTY3NDkyNS8zMjgzNzYzMjctM2EyNTUyZjgtZjQyMC00N2U4LTk2YWMtZmZlMWQwNGJiZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZWE5ODBjMTc5YTQ3OGFiNDI2ZWZkMDBlM2RlOGY1YTcxY2QzM2RhNDNlZDE0ZTI4YzNhMDlhYjI2YTBjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oostIZljsf_lqp7fxw_j2Jz4XmNW_vaZYSNGtZr0X0U) ![image](https://private-user-images.githubusercontent.com/35674925/328741452-658d52c4-e909-4377-aed4-b9a27e7085c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIyNzMsIm5iZiI6MTcxNTE2MTk3MywicGF0aCI6Ii8zNTY3NDkyNS8zMjg3NDE0NTItNjU4ZDUyYzQtZTkwOS00Mzc3LWFlZDQtYjlhMjdlNzA4NWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NjhmNTY1YTM2ZWQwOGIyYzk4ZTZiMzQxZmU5ZjdkMDNiNjhiOGU0ZjlhN2Q3NjQxNDllZjdlNTQwOGI5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lIjci2K6WZyRd4x1bWn0sVO7GyuYqwnEKYAUeEBVrY)

**Comment by toyosky** [comment]
> > http_proxy_port
> 
> 请问你现在还能正常使用吗？

请问你最后能用了吗？跪谢

**Comment by qiuzhen8484** [comment]
> > > http_proxy_port
> > 
> > 
> > 请问你现在还能正常使用吗？
> 
> 请问你最后能用了吗？跪谢

不能

**Comment by liang-zijian** [comment]
I find a new way to solve this problem😄.It may not work for everyone.

- Windows 11
- Clash v0.20.39
- python 3.10
- poe-api-wrapper (**not proxy version!**)

```python
from poe_api_wrapper import PoeExample
import os
os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
tokens = {
    'b': 'xxx', 
    'lat': 'xxx'
}
PoeExample(cookie=tokens).chat_with_bot()
```
And the most important thing is to set Clash like this(**turn off system proxy, switch to Global mode and select an available node**):
![image](https://github.com/snowby666/poe-api-wrapper/assets/81151149/afd55754-d3c8-471e-a050-8bbdabe01c75)

**Comment by toyosky** [comment]
> I find a new way to solve this problem😄.It may not work for everyone.
> 
> * Windows 11
> * Clash v0.20.39
> * python 3.10
> * poe-api-wrapper (**not proxy version!**)
> 
> ```python
> from poe_api_wrapper import PoeExample
> import os
> os.environ["http_proxy"] = "http://127.0.0.1:7890"
> os.environ["https_proxy"] = "http://127.0.0.1:7890"
> tokens = {
>     'b': 'xxx', 
>     'lat': 'xxx'
> }
> PoeExample(cookie=tokens).chat_with_bot()
> ```
> 
> And the most important thing is to set Clash like this(**turn off system proxy, switch to Global mode and select an available node**): ![image](https://private-user-images.githubusercontent.com/81151149/331762009-afd55754-d3c8-471e-a050-8bbdabe01c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTg2NTIsIm5iZiI6MTcxNjAxODM1MiwicGF0aCI6Ii84MTE1MTE0OS8zMzE3NjIwMDktYWZkNTU3NTQtZDNjOC00NzFlLWEwNTAtOGJiZGFiZTAxYzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA3NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjNmMzQ5YzBkNjZiZWNiZDViZGI5MGY1ZWNiOTk3MzQ2ZGY5N2JhNzAwOTJkMWMzYmQ3YjhmOGYwMTE1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6xtI3Da6zl1U1yekVi0O0JJYIJ06Ke0_E6Cg_hXpWQ)

Thank you very much. I make it. love you

**Comment by owlsan49** [comment]
> I find a new way to solve this problem😄.It may not work for everyone.
> 
> * Windows 11
> * Clash v0.20.39
> * python 3.10
> * poe-api-wrapper (**not proxy version!**)
> 
> ```python
> from poe_api_wrapper import PoeExample
> import os
> os.environ["http_proxy"] = "http://127.0.0.1:7890"
> os.environ["https_proxy"] = "http://127.0.0.1:7890"
> tokens = {
>     'b': 'xxx', 
>     'lat': 'xxx'
> }
> PoeExample(cookie=tokens).chat_with_bot()
> ```
> 
> And the most important thing is to set Clash like this(**turn off system proxy, switch to Global mode and select an available node**): ![image](https://private-user-images.githubusercontent.com/81151149/331762009-afd55754-d3c8-471e-a050-8bbdabe01c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY4NDYsIm5iZiI6MTcxNjAyNjU0NiwicGF0aCI6Ii84MTE1MTE0OS8zMzE3NjIwMDktYWZkNTU3NTQtZDNjOC00NzFlLWEwNTAtOGJiZGFiZTAxYzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMmI4YjQ5NWQxYmRiMzE3NjQ2MWU0YmRhNDIzMDdhNjI0MDYxZTMyZjAxZmQ2MGQyYTVkNWNmZjEwYzQ4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DA1cV23i6BtSW4ZvHTS2CJ8R09QoTtRheEkIlrcsRQg)

It works for me

**Comment by snowby666** [comment]
This is be fixed in v.1.5.4
