### ISSUE TITLE
RuntimeError: Timed out waiting for websocket to connect.

### ISSUE THREAD

**Issue by ngbruce** [snowby666/poe-api-wrapper#47]
Env: 
Pycharm + anaconda

Network: 
proxy which works fine for EDGE broswer

Issue:
When I try run a demo as below， it return an error of 
"RuntimeError: Timed out waiting for websocket to connect."

demo code:
`
from poe_api_wrapper import PoeExample
`
`
token = "my_cookies_copied_from_EDGE"
`
`
PoeExample(token).chat_with_bot()
`

**Comment by snowby666** [comment]
Is it working in the new release?

**Comment by ngbruce** [comment]
> Is it working in the new release?

still no good.
I hard reset the project to latest but still get error:
Traceback (most recent call last):
  File "D:\MY_DOCUMENTS\Python_Projs\My_Apps\poe-api-wrapper\myTest.py", line 3, in <module>
    PoeExample(token).chat_with_bot()
  File "D:\MY_DOCUMENTS\Python_Projs\My_Apps\poe-api-wrapper\poe_api_wrapper\example.py", line 6, in __init__
    self.client = PoeApi(cookie=self.cookie)
  File "D:\MY_DOCUMENTS\Python_Projs\My_Apps\poe-api-wrapper\poe_api_wrapper\api.py", line 147, in __init__
    self.connect_ws()
  File "D:\MY_DOCUMENTS\Python_Projs\My_Apps\poe-api-wrapper\poe_api_wrapper\api.py", line 263, in connect_ws
    raise RuntimeError("Timed out waiting for websocket to connect.")
RuntimeError: Timed out waiting for websocket to connect.

**Comment by snowby666** [comment]
I see. I think the ws connection has some issues when you are behind a proxy. I will try to reproduce this and do further research

**Comment by snowby666** [comment]
I will change the get_form_key method

**Comment by ngbruce** [comment]
> get_formkey()

What I mean is, the get_formkey() function is fine.
It was just a test shows that the peoject can go through the proxy and return the formkey. I think the problem is some where after getting the formkey, some thing wrong with ws with proxy.
