### ISSUE TITLE
 Error while getting response from PoeApi: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bluusun** [snowby666/poe-api-wrapper#48]
Really odd issue:

Works for me:

previous_messages = client.get_previous_messages(bot, chatId=95544182, count=1)

But this does NOT work for me:

 chat="95544182"
 previous_messages = client.get_previous_messages(bot, chatId=chat, count=1)

 Error while getting response from PoeApi: 'NoneType' object is not subscriptable.

Any ideas?

**Comment by snowby666** [comment]
chatId is int type

**Comment by bluusun** [comment]
> chatId is int type

Duh! Thanks :) Works now.
