### ISSUE TITLE
client.send_message() BUG

### ISSUE THREAD

**Issue by YonQua** [snowby666/poe-api-wrapper#5]
bot = "a2_2"
The client.send_message() method, when passed the chatCode parameter, does not work. Using the chatId parameter instead works fine.

BUG
client.send_message(bot, message, chatCode=history[f'{bot}'][0]['chatCode'])
OK
client.send_message(bot, message, chatId=history[f'{bot}'][0]['chatId'])

**Comment by snowby666** [comment]
I've just fixed them. I changed the return type of send_message to a dict of response, chatId, and chatCode for better stability.
