### ISSUE TITLE
Timeout and failed to get the reply

### ISSUE THREAD

**Issue by ngoduyvu** [snowby666/poe-api-wrapper#50]
Hi today (20/09) I found that I used the send_message with Attached documents keep failing and timeout.

Here is the running code example:
![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/3167214d-f8da-4f5c-8085-40a174f6d5b6)

I checked on Poe.AI and I can see the website showed the response but the code failed to get the response
![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/12f26ea8-4e31-4c0c-a38d-8baeff4badb1)

The problem only appear on the message which has attach document, normal prompts are fine. I tried with different Bot event Chat GPT4 and the issue still happen.

Environment: Google Colab
Python: 3.10
Latest version

**Comment by snowby666** [comment]
Can you check your token again. I've just tried this in Google Colab and it worked fine for me,

![image](https://github.com/snowby666/poe-api-wrapper/assets/112873281/f23a8b24-c135-4885-bb39-24de0f6edd02)

**Comment by ngoduyvu** [comment]
Hi @snowby666 , thanks for replying. Yes, it is working now. I am really sure that I restarted a few time when I encouter the error. May be something with the server of POE. Thanks so much for amazing work.

**Comment by snowby666** [comment]
Glad it helped
