### ISSUE TITLE
Time out waitting for response

### ISSUE THREAD

**Issue by khiempm209** [snowby666/poe-api-wrapper#51]
![Screenshot 2023-09-20 185757](https://github.com/snowby666/poe-api-wrapper/assets/119430607/2a2bc18e-d2e8-41e3-8b12-71f1abb0560f)
I ran poe-api in kaggle notebook and i got the correct token in quora with the same gmail in poe.com. But i got this retrying error multiple times. How can i fix this ? I set 40 second for the time out of "send_message" function.

**Comment by snowby666** [comment]
did you update the lib?

**Comment by summer2009** [comment]
no m-b key in cookies!!!

**Comment by khiempm209** [comment]
@snowby666 The version I last used was 1.2.3. So the higher version will fix that problem?

**Comment by snowby666** [comment]
I ran this on kaggle notebook and it worked normally
![image](https://github.com/snowby666/poe-api-wrapper/assets/112873281/7fb3ef69-dc4a-4519-95a4-2071a935dbbd)

**Comment by bluusun** [comment]
Same problem here. To see the issue. Use a 100 page document and request beaver or a2_2. Request a 800 word summary.  This will duplicate the request endlessly via the repo instead of simply waiting as beaver and a2_2 usually need 1-2 minutes to reply.
