### ISSUE TITLE
StableDiffusionXL messages https://poe.com/settings

### ISSUE THREAD

**Issue by noseon** [snowby666/poe-api-wrapper#52]
StableDiffusionXL messages https://poe.com/settings 
Create a way to generate photos in your code

**Comment by johnd0e** [comment]
As I can see it is already possible, in usual way.
Just chat with `StableDiffusionXL` bot, and get picture's url

**Comment by snowby666** [comment]
This is bot is currently private. Maybe Poe will release it soon

**Comment by noseon** [comment]
[https://qph.cf2.quoracdn.net/main-98992179_12622034995_1.png?w=1024&h=1024](url)
Before it was proven, I managed to generate this photo

**Comment by noseon** [comment]
Stable Diffusion chat is no longer private, adjust the new function now

**Comment by snowby666** [comment]
Im writing a new feature for bots group chat and fixing some issues with the retry logic. I will update the api soon ^^

**Comment by noseon** [comment]
![photo_2023-09-29_14-21-04](https://github.com/snowby666/poe-api-wrapper/assets/11984221/99f46ef2-4731-4357-8648-864c04247dc2)
manage to fix poe on telegram effectively

**Comment by snowby666** [comment]
This is handled in the latest release
