### ISSUE TITLE
Bot not found

### ISSUE THREAD

**Issue by detherminal** [snowby666/poe-api-wrapper#53]
Custom bot's are giving not found error.

```
Traceback (most recent call last):
  File "/home/cm/.local/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 773, in delete_chat
    chatdata = self.get_chat_history(bot=bot)['data'][bot]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
```

I am able to talk with the bot in web but I am not able to connect to them in API.

**Comment by snowby666** [comment]
if you use delete_chat, make sure the bot has exisiting threads before deleting

**Comment by detherminal** [comment]
> if you use delete_chat, make sure the bot has exisiting threads before deleting

Thanks, working. <3
