### ISSUE TITLE
Awsome! What's the technical difference between this project and ading2210/poe-api?

### ISSUE THREAD

**Issue by magician-blue** [snowby666/poe-api-wrapper#55]

**Comment by snowby666** [comment]
Technically, this project depends on the api of quora.com not poe.com. So its much better (personally) to fetch the formkey, which changes daily with "not a fixed" salt on poe.com. Another plus is that the header to make requests is app-based so there's less chance of getting rate limit or account suspended (quite sure). Other than that, some of the functions are rebuilt and new features are added.
