### ISSUE TITLE
Retrying request 1/3 times

### ISSUE THREAD

**Issue by bluusun** [snowby666/poe-api-wrapper#58]
I need to switch off this Retrying asap. When queries a slow (does not matter what timeout I set) it keeps retrying and wasting requests for me. The next still times out (these are queries with longer documents).

Retrying request 1/3 times...

It is much better for me to query by chat ID as the content will be available eventually.

How can I switch off this behavior? Just went through 1000 paid queries in a few minutes :(

**Comment by snowby666** [comment]
I'm rewriting the retry function since poe added new logic to their api. The current one checks for error message then delete it and resend the message. But sometimes the text is not fully generated so theres a dead lock somewhere.

**Comment by bluusun** [comment]
Thanks! For now I uninstalled pip and clone repo and changed value of retry_attempts.

**Comment by bluusun** [comment]
Made changes in code but same behavior. This is so frustrating since I also never get the results...

![iDB 2023-09-23 at 8 01 31 PM](https://github.com/snowby666/poe-api-wrapper/assets/65051271/ac35fab9-1030-4bc1-853d-3e323c83b3ee)

**Comment by bluusun** [comment]
Is there any reliable way to switch this behavior off?

**Comment by bluusun** [comment]
Latest version seems to have that issue less, did you change something?

**Comment by snowby666** [comment]
This is fixed in the new version
