### ISSUE TITLE
https://poe.com/poe update your code to accept the 21 bots on the poe page

### ISSUE THREAD

**Issue by noseon** [snowby666/poe-api-wrapper#59]
https://poe.com/poe update your code to accept the 21 bots on the poe page

**Comment by johnd0e** [comment]
Related to #56

**Comment by mishra-saksham** [comment]
@johnd0e 
{
    'Assistant': 'capybara',
    'Claude-instant-100k': 'a2_100k',
    'Claude-2-100k': 'a2_2',
    'Claude-instant': 'a2',
    'ChatGPT': 'chinchilla',
    'ChatGPT-16k': 'agouti',
    'GPT-4': 'beaver',
    'GPT-4-32k': 'vizcacha',
    'Google-PaLM': 'acouchy',
    'Llama-2-7b': 'llama_2_7b_chat',
    'Llama-2-13b': 'llama_2_13b_chat',
    'Llama-2-70b': 'llama_2_70b_chat',
    'Code-Llama-7b': 'code_llama_7b_instruct',
    'Code-Llama-13b': 'code_llama_13b_instruct',
    'Code-Llama-34b': 'code_llama_34b_instruct',
    'ChatGPT-Instruct': 'chinchilla_instruct',
    'StarCoderChat':'starcoderchat',
    'Dolly-V2-12B':'dollyv212b',
    'Nous-Hermes-L2-13b':'noushermesl213b',
    'Nous-Hermes-13b':'noushermes13b',
    'Solar-0-70b':'upstage_solar_0_70b_16bit'
} 
Here update the list in API's Section and remember to update the setup.
