### ISSUE TITLE
Connection to remote host was lost

### ISSUE THREAD

**Issue by josephrlandry** [snowby666/poe-api-wrapper#69]
`
from poe_api_wrapper import PoeApi

POE_ACCESS_KEY = "<m-b from quora>"

client = PoeApi(POE_ACCESS_KEY)

print(client.get_chat_history()['data'])
`

The code above always leads to:

![screenshot 06-10-2023 23 13 35](https://github.com/snowby666/poe-api-wrapper/assets/143529666/a3799dea-00a8-425b-9b89-59ecf09821f3)

Is it just me? I'm using version 1.3.0

**Comment by snowby666** [comment]
Can you specify your environment here?
Thanks

**Comment by d1h1r1** [comment]
I'm also having this issue, python 3.11, poe-api-wrapper 1.3.2

**Comment by laruss** [comment]
same for me.
McBook M1, MacOS 13.4.1 on , python3.10, using venv

**Comment by laruss** [comment]
Added more logs, here's the reasson:
`Websocket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)`

**Comment by laruss** [comment]
@snowby666 this could help in such cases
`import ssl`
`    def ws_run_thread(self):
        if not self.ws.sock:
            kwargs = {"sslopt": {"cert_reqs": ssl.CERT_NONE}}
            self.ws.run_forever(**kwargs)
`

or maybe you could forward ssl to PoeApi.__init__ params.

**Comment by snowby666** [comment]
Thanks for your suggestion. This is added in the new version as temp method. I'll work on other approaches.
