### ISSUE TITLE
Too many open files error caused by poe-api-wrapper

### ISSUE THREAD

**Issue by hansfzlorenzana** [snowby666/poe-api-wrapper#71]
I've seen a similar issue with this but is now closed with no specific resolution.

I've been receiving this particular error when requesting continuously from the api wrapper. Here is the error:

```
2023-10-09 13:13:03.788 | WARNING  | poe_api_wrapper.api:on_ws_close:298 - Connection to remote host was lost. Reconnecting...
ERROR:websocket:[Errno 24] Too many open files - goodbye
```

I believe this is caused by the api. I think there is some implementation in the api script that does not let files close properly.

After this error, another error shows

```
Exception ignored in: <function PoeApi.__del__ at 0x7fbe815b6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/poe_api_wrapper/api.py", line 154, in __del__
AttributeError: 'PoeApi' object has no attribute 'client'

```

**Comment by snowby666** [comment]
This is because you are opening too many sockets concurrently. Try closing unused ones so that you don't exceed the maximum number of open files allowed by the operating system

**Comment by hansfzlorenzana** [comment]
I see. Thanks. May I know how to do it? Should I use the __del__() or the disconnect_ws()?

**Comment by xzwthu** [comment]
I think the best solution is to add t.join() at the end every time a new thread is created using t.start(). This ensures that the main thread waits for all the child threads to finish executing before continuing with the subsequent code. t.join() blocks the main thread until the corresponding child thread completes its execution and releases the blockage. This helps avoid forcibly terminating the child threads before the main thread ends, ensuring proper execution of the threads and correct resource release.
