### ISSUE TITLE
Server Error when trying to send message

### ISSUE THREAD

**Issue by ngoduyvu** [snowby666/poe-api-wrapper#72]
Hi, I used the python code for the whole morning, and everything is fine. But all sudden It keeps getting error. The code returns Errors Server

![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/a7fcc7a5-ecbd-43fa-a241-033081515211)

I try to use the POE.AI and it still run normally

![image](https://github.com/snowby666/poe-api-wrapper/assets/13109150/1eadae61-9cf3-4b45-998d-3c08e78e579e)

I hope Quara dont implement anything to prevent us from using Python code to send message.

**Comment by ngoduyvu** [comment]
The environment is Google Colab, python 3.10 and latest library version

**Comment by ngoduyvu** [comment]
I think it is becaus of busy time, I just open POE AI again I found the conversation created. I guess the server did not response even when I saw the library retried 3 times. Is there a way I can set the retry and wait time?

**Comment by snowby666** [comment]
Yes, you can set the timeout like this `send_message(bot, message, timeout=15)`

**Comment by ngoduyvu** [comment]
Cheer Thanks
