### ISSUE TITLE
Cancelling message returns an error

### ISSUE THREAD

**Issue by samuelchristlie** [snowby666/poe-api-wrapper#81]
I've been using `client.cancel_message(chunk)` to cancel messages but after recent updates, it now returns the following error
```
  File "xxx", line 159, in <module>
    poe.cancel_message(chunk)
  File "xxx\lib\site-packages\poe_api_wrapper\api.py", line 900, in cancel_message
    variables = {"messageId": chunk["messageId"], "textLength": len(chunk["text"]), "linkifiedTextLength": len(chunk["linkifiedText"])}
KeyError: 'linkifiedText'
```

**Comment by snowby666** [comment]
Thanks for the issue. I've just reviewed your PR and theres a syntax error with the spare ")" so I can't merge the PR. 

But I'd added this in the new update.

**Comment by samuelchristlie** [comment]
Sorry, must've missed it when pasting changes. That'll do, thanks!

On Nov 29, 2023 10:16 PM, Ngô Đình Gia Bảo ***@***.***> wrote:

Thanks for the issue. I've just reviewed your PR and theres a syntax error with the spare ")" so I can't merge the PR.

But I'd added this in the new update.
