### ISSUE TITLE
Add gemini pro in poe-api-wrapper

### ISSUE THREAD

**Issue by hoangphu7122002** [snowby666/poe-api-wrapper#89]
Hi,

Can you please add Gemini Beta to the Available Default Bots list? It's already publicly available in the POE web interface.

Thank you, and I hope you can respond soon!

**Comment by snowby666** [comment]
Hi,
Its already there. You can pass its display name `gemini-pro` as the bot param. 
```py
client = PoeApi('Your_Token')
for chunk in client.send_message('gemini-pro', 'Nice to meet you.'):
          print(chunk['response'], end='', flush=True)
```

Since there're only some specific bots that require unique names when call them, so I listed them in the README.md
Hope this helps
