### ISSUE TITLE
Rate limit exceeded for sending requests to poe.com.

### ISSUE THREAD

**Issue by KenStevan** [snowby666/poe-api-wrapper#93]
File "/usr/local/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 159, in __init__
    self.connect_ws()
  File "/usr/local/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.
This error keeps appearing but I guarantee that my token can be used because I can use it on other hosts. Is the IP access station too frequent?

**Comment by 4l3dx** [comment]
I had the same issue, the solution for me was changing "content" to "data":
https://github.com/snowby666/poe-api-wrapper/blob/497f20aecb5a2a13aa08b346b43bba8cd4c9ad48/poe_api_wrapper/api.py#L187

**Comment by lemaidig** [comment]
my windows 10(22H2) makes the same error but another machine that using windows 11 runs well  @snowby666

**Comment by Barnacules** [comment]
I'm hitting the same issue here with my account. I tried both my Quora and PoE cookies with no luck sadly. If anyone knows how to resolve this, please let me know. My PoE account was signed up through iOS PoE app and just doesn't seem to do anything other than tell me rate limit exceeded. However, when I login to the poe.com website everything works so I don't understand why it's having issues.

**Comment by EugeneBoondock** [comment]
Remove the connected gmail account from your quora settings

**Comment by satounity** [comment]
> Remove the connected gmail account from your quora settings

Please explain in detail how to do

**Comment by EugeneBoondock** [comment]
> > Remove the connected gmail account from your quora settings
> 
> Please explain in detail how to do 

Go to Quora.com, then go to your settings, you'll see Google accounts that are connected to your quora, remove the one that's there...

**Comment by satounity** [comment]
> > > Remove the connected gmail account from your quora settings
> > 
> > 
> > Please explain in detail how to do
> 
> Go to Quora.com, then go to your settings, you'll see Google accounts that are connected to your quora, remove the one that's there...


I have deleted my account.
Apparently it will be deleted after 14 days.

Should I wait 14 days?

**Comment by samuelchristlie** [comment]
Any input from @snowby666? What does the pin mean? Is unlinking my Google account supposed to solve the problem? I unlinked mine and issues still persists

**Comment by snowby666** [comment]
> Any input from @snowby666? What does the pin mean? Is unlinking my Google account supposed to solve the problem? I unlinked mine and issue still persists

if it still doesnt work, I'd recommend using quora token instead of poe token.

**Comment by Cecilia-zwq** [comment]
I have this issue too. I tried quora and poe token both, but it still goes wrong.

**Comment by DuyguA** [comment]
I have this issue too, neither Quora nor Poe token works for me. I tried disconnecting my Google account from Quora, that didn't work either.
