### ISSUE TITLE
get_available_knowledge is limited to the 5 last entries

### ISSUE THREAD

**Issue by baigouy** [snowby666/poe-api-wrapper#97]
Great tool, it is very useful to me, so really thanks for it.

I noticed that when I call:

 `client.get_available_knowledge(botName=bot)`

it only returns the first 5 entries (pdfs files in my case) and ignores the remaining (pages of) entries. Is there a way to get the complete knowledge base or a given number of entries ?

thanks

**Comment by XenocodeRCE** [comment]
Hello, I try to fix this problem today. To show you how I do : 

The **get_available_knowledge** def here https://github.com/snowby666/poe-api-wrapper/blob/3f3c631007d44d75200557bae2588c2662fbdcce/poe_api_wrapper/api.py#L1080 use a query the webbrowser doesn't seems to use to grab source content

The webbrowser do this when visiting the edit page : 
```
{"queryName":"BotKnowledgeSourcesModalPaginationQuery","variables":{"after":"5","first":10,"id":"Qm90OjMzNzUyNjE="},"extensions":{"hash":"c02cd4af451d17837143f8572e24b5b9624c2e023bb98bfc1217bde9aedec1ad"}}
```

I think the "5" limit stands here, I am sure we can increase it. I also saw a "next page" thing : 

```
"pageInfo": {"endCursor": "5", "hasNextPage": true}
```


however when I increase this "5" value I still got stuck with 5 elements in a row 👎 

```python
 def get_available_knowledge(self, botName: str):
        variables = {"botName": botName}
        response = self.send_request('gql_POST', 'EditBotIndexPageQuery', variables)
        theID = response["data"]["viewer"]["id"]
        variables = {"after": "10", "first": 20, "id": theID }
        responseX = self.send_request('gql_POST', 'BotKnowledgeSourcesModalPaginationQuery', variables)
        print(responseX)
```

I'll keep you updated

**Comment by snowby666** [comment]
Now you can fetch more entries
